<?php
/**
 * Copyright © MageKey. All rights reserved.
 */

?>
<?php if ($block->hasItems()) : ?>
<div class="block widget block-mgk-brochures">
    <?php if ($block->getTitle()): ?>
    <div class="block-title">
        <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
    </div>
    <?php endif; ?>
    <div class="block-content">
        <?= $block->getItemHtml() ?>
    </div>
</div>
<?php endif; ?>
